spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zzy200013
    #连接池配置
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    hikari:
      max-lifetime: 500000
  mvc:
    view:
      prefix: /
      suffix: .jsp
#Mybatis
mybatis:
  #设置别名
  type-aliases-package: com.todo.pojo
  #ָ指定myBatis的核心配置文件与Mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true


  #mysqld --defaults-file="C:\ProgramData\MySQL\MySQL Server 8.0\my.ini" -console -skip-grant-tables