spring:
  datasource:
    url: jdbc:mysql://139.159.133.187:3306/todo?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zzy200013
  mvc:
    view:
      prefix: /
      suffix: .jsp
#Mybatis
mybatis:
  #设置别名
  type-aliases-package: com.todo.pojo
  #ָ指定myBatis的核心配置文件与Mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true


  #mysqld --defaults-file="C:\ProgramData\MySQL\MySQL Server 8.0\my.ini" -console -skip-grant-tables